---
title: "PCA_plots"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
```

## PCA and plots colored by activation

```{r}

#Loading necessary libraries 
library(factoextra)
library(FactoMineR)
library(ggplot2)
library(tidyverse)
library(readxl)

```

##PCA of proteomics 

```{r}

#Loading and formatting data
raw_data <- read.csv("/home/aosterberg/Documents/DI_työ/PEVproteomics.csv",header = TRUE, dec = ",")
colnames(raw_data) <- c("protein", "US_PEV_1","US_PEV_2","US_PEV_3","GPVI_PEV_1", "GPVI_PEV_2", "GPVI_PEV_3", "CLEC2_PEV_1","CLEC2_PEV_2","CLEC2_PEV_3","TC_PEV_1","TC_PEV_2","TC_PEV_3")
test_data <- raw_data[,2:13]
prot_data <- as.matrix(test_data)

#Assigning groups for coloring samples 
prot_groups <- c("US", "US","US", "GPVI", "GPVI","GPVI", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple")

#Performing PCA analysis
pca_data <- PCA(t(prot_data), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE) #plotting PCs
eigenvalues <- pca_data$eig #storing eigenvalues
summary(pca_data)

#Plotting the data
fviz_pca_ind(pca_data,
             col.ind = prot_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of proteomics", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal() + scale_shape_manual(values = rep(16, length(unique(prot_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+ theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))


```
## PCA of inflammation panel 

```{r}

#Loading and formatting the data 
raw_data <- read.csv("/home/aosterberg/Documents/DI_työ/PEVinflammationpanel.csv",header = TRUE)
colnames(raw_data) <- c("protein", "US_PEV_1","US_PEV_2","US_PEV_3", "US_PEV_4", "GPVI_PEV_1", "GPVI_PEV_2", "GPVI_PEV_3", "GPVI_PEV_4", "CLEC2_PEV_1","CLEC2_PEV_2","CLEC2_PEV_3","TC_PEV_1","TC_PEV_2","TC_PEV_3")
test_data <- raw_data[,2:15] 
PEA_data <- as.matrix(test_data)

#Adding groups for coloring the samples in the plot 
PEA_groups <- c("US", "US","US", "US", "GPVI", "GPVI", "GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "TC", "TC","TC")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple")

#Performing the analysis
pca_data <- PCA(t(PEA_data), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE) #plotting PCs
eigenvalues <- pca_data$eig #extracting eigenvalues

#Plotting the PCA data, coloring by groups and showing variance explained by each principal component
fviz_pca_ind(pca_data,
             col.ind = PEA_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of PEA", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal()+ scale_shape_manual(values = rep(16, length(unique(PEA_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 3))) + theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))


```
## PCA of macrophage secretome (cytokines) 
-6h with both no PEV treatment and without PEV treatments
-24h with both no PEV treatment and without PEV treatments


```{r}
#PCA for data after 6h including 2 no PEV samples (2 others are missing in this dataset) after 6h
raw_6h <- read_excel("/home/aosterberg/Documents/DI_työ/data/TableS2.xlsx", sheet = 2) %>% as.data.frame()
colnames(raw_6h) <- c("secretome", "US_PEV_1", "US_PEV_2", "US_PEV_3", "US_PEV_4","GPVI_PEV_1", "GPVI_PEV_2", "GPVI_PEV_3", "GPVI_PEV_4", "CLEC2_PEV_1","CLEC2_PEV_2","CLEC2_PEV_3", "CLEC2_PEV_4", "TC_PEV_1","TC_PEV_2","TC_PEV_3", "TC_PEV_4", "no_PEV_1","no_PEV_2","no_PEV_3","no_PEV_4")
rownames(raw_6h) <- raw_6h[,1]
cytokine_6h <- raw_6h[,2:19] %>% as.matrix()
cytokine_groups <- c("US", "US", "US", "US", "GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC", "no_PEV", "no_PEV")

sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple", "no_PEV" = "orange")

#Performing analysis and plotting results
pca_data <- PCA(t(cytokine_6h), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

fviz_pca_ind(pca_data,
             col.ind = cytokine_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of macrophage secretome after 6h", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal() + scale_shape_manual(values = rep(16, length(unique(cytokine_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))

#Including only PEV samples at 6h time point

PEVcytokine_6h <- raw_6h[,2:17] %>% as.matrix() #dropping NO PEV columns

PEVcytokine_groups <- c("US", "US", "US", "US", "GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple")

#Performing analysis and plotting data
pca_data <- PCA(t(PEVcytokine_6h), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

fviz_pca_ind(pca_data,
             col.ind = PEVcytokine_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of macrophage secretome of PEV samples after 6h", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal() + scale_shape_manual(values = rep(16, length(unique(cytokine_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))



#including no PEV samples after 24 h 
raw_24h <- read.csv("/home/aosterberg/Documents/DI_työ/cytokine24h.csv",header = TRUE)
colnames(raw_24h) <- c("secretome", "US_PEV_1", "US_PEV_2", "US_PEV_3", "US_PEV_4","GPVI_PEV_1", "GPVI_PEV_2", "GPVI_PEV_3", "GPVI_PEV_4", "CLEC2_PEV_1","CLEC2_PEV_2","CLEC2_PEV_3", "CLEC2_PEV_4", "TC_PEV_1","TC_PEV_2","TC_PEV_3", "TC_PEV_4", "no_PEV_1","no_PEV_2","no_PEV_3","no_PEV_4")
cytokines_24h <- raw_24h[,2:21] %>% as.matrix()


cytokine_groups <- c("US", "US", "US", "US", "GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC", "no_PEV", "no_PEV", "no_PEV", "no_PEV")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple", "no_PEV" = "orange")

#Performing analysis and plotting results
pca_data <- PCA(t(cytokines_24h), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

fviz_pca_ind(pca_data,
             col.ind = cytokine_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of macrophage secretome after 24 h", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal()+ scale_shape_manual(values = rep(16, length(unique(cytokine_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))


#Including only PEV samples at 24h timepoint

PEVcytokines_24h <- raw_24h[,2:17] %>% as.matrix() #dropping NO PEV columns

cytokine_groups <- c("US", "US", "US", "US", "GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple")


pca_data <- PCA(t(PEVcytokines_24h), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

fviz_pca_ind(pca_data,
             col.ind = cytokine_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of macrophage secretome of PEV samples after 24 h", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal() + scale_shape_manual(values = rep(16, length(unique(cytokine_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))

```
## PCA of miRNA data
-first again including platelet samples and then with only PEV samples

```{r}
#PCA of miRNA data including platelet samples 
raw_miRNA <- read.csv("/home/aosterberg/Documents/DI_työ/PEVmiRNA.csv",header = TRUE)
colnames(raw_miRNA) <- c("miRNA", "GPVI_PEV_1", "GPVI_PEV_2", "GPVI_PEV_3", "GPVI_PEV_4", "CLEC2_PEV_1","CLEC2_PEV_2","CLEC2_PEV_3", "CLEC2_PEV_4", "TC_PEV_1","TC_PEV_2","TC_PEV_3", "TC_PEV_4", "US_PEV_1","US_PEV_2","US_PEV_3","US_PEV_4", "Platelet_1", "Platelet_2", "Platelet_3", "Platelet_4")
miRNA_data <- raw_miRNA[,2:21] %>% as.matrix()

miRNA_groups <- c("GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC", "US", "US","US", "US","Platelet", "Platelet","Platelet","Platelet")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple", "Platelet" = "deeppink")

#Performing PCA and plotting results
pca_data <- PCA(t(miRNA_data), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

fviz_pca_ind(pca_data,
             col.ind = miRNA_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of miRNA", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal()+ scale_shape_manual(values = rep(16, length(unique(miRNA_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))

#Including only PEV samples 

PEVmiRNA_data <- raw_miRNA[,2:17] %>% as.matrix()


PEVmiRNA_groups <- c("GPVI", "GPVI","GPVI", "GPVI", "CLEC2", "CLEC2", "CLEC2", "CLEC2","TC","TC","TC","TC", "US", "US","US", "US")
sample_colors <- c("CLEC2" = "red", "GPVI" = "green", "TC" = "blue", "US"= "purple")

pca_data <- PCA(t(PEVmiRNA_data), scale.unit = TRUE, graph = FALSE)
fviz_eig(pca_data, addlabels = TRUE)
eigenvalues <- pca_data$eig

summary(pca_data)
fviz_pca_ind(pca_data,
             col.ind = PEVmiRNA_groups, # color by groups
             palette = sample_colors, mean.point = FALSE, repel = TRUE,
             legend.title = "Groups")+labs(title = "PCA of PEVs miRNA", x= paste0("PC1 (",round(eigenvalues[1,2],2),"%)"), y= paste0("PC2 (",round(eigenvalues[2,2],2),"%)")) + theme_minimal() + scale_shape_manual(values = rep(16, length(unique(PEVmiRNA_groups)))) + guides(color = guide_legend(override.aes = list(shape = 16, size = 4)))+theme(axis.title.x = element_text(size = 13, color = "black"), axis.title.y = element_text(size = 13, color = "black"), axis.text.x = element_text(size = 13, color = "black"), axis.text.y = element_text(size = 13,  color = "black"),legend.text = element_text(size = 12), legend.title = element_text(size  = 12))

```

