---
title: "MOFA of proteomics and miRNA"
author: "Anna Österberg"
date: "2024-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

## Running MOFA on filtered and normalized proteomics and miRNA 
-only including PEV samples 

```{r}
#Loading needed libraries
library(tidyverse)
library(MOFA2)
library(data.table)
library(reticulate)

#Loading the pre-processed data and checking that it is correct
prot_data <-read.csv(file.choose(), header = TRUE, row.names = 1)
boxplot(prot_data[,-1])
miRNA_data <- read.csv(file.choose(),header = TRUE, row.names = 1)
boxplot(miRNA_data[,-1])

mofa_data <- list(view1 = as.matrix(prot_data), view2= as.matrix(miRNA_data)) #creating a list of matrices of protein and miRNA data

#creating MOFA object
MOFA_object <- create_mofa_from_matrix(mofa_data)
views_names(MOFA_object) <- c("proteins","miRNA")
plot_data_overview(MOFA_object)
print(MOFA_object)

#Setting model and training options 
data_opts <- get_default_data_options(MOFA_object) 
head(data_opts)

model_opts <- get_default_model_options(MOFA_object)
model_opts$num_factors <- 6
head(model_opts)

train_opts <- get_default_training_options(MOFA_object)
train_opts$convergence_mode <-"slow"
set.seed <- 42
head(train_opts)

#We train the model 
MOFA_object <- prepare_mofa(
  object = MOFA_object,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts
)

#In terminal we ran commands conda create -n mofa_env10 python=3.10, conda activate mofa_env10 (you don't have to create a new environment each time, reticulate package downloaded does not seem to work with python 3.12 therefore we use python 3.10)
reticulate::use_condaenv("mofa_env10")
outfile = file.path("/home/aosterberg/Documents/DI_työ", "top100MOFAmodel.hdf5")
MOFAobject.trained <- run_mofa(MOFA_object, outfile=outfile, use_basilisk=FALSE)
```
### We then plot variance decomposition for the model and extract factors 

```{r}
model <- load_model(outfile, remove_inactive_factors = FALSE)
plot_variance_explained(model, x="view", y="factor")

#we create a dataframe for each factor 
factor1_df <- get_factors(model, factors = 1, as.data.frame = TRUE)
factor2_df <- get_factors(model, factors = 2, as.data.frame = TRUE)
factor3_df <- get_factors(model, factors = 3, as.data.frame = TRUE)
factor4_df <- get_factors(model, factors = 4, as.data.frame = TRUE)
factor5_df <- get_factors(model, factors = 5, as.data.frame = TRUE)
factor6_df <- get_factors(model, factors = 6, as.data.frame = TRUE)

#we drop columns group and factor 
factor1_df <- factor1_df %>% select(-group, -factor)
factor2_df <- factor2_df %>% select(-group, -factor)
factor3_df <- factor3_df %>% select(-group, -factor)
factor4_df <- factor4_df %>% select(-group, -factor)
factor5_df <- factor5_df %>% select(-group, -factor)
factor6_df <- factor6_df %>% select(-group, -factor)


#we merge the dataframes into one and save it as a csv file
factors_df <- Reduce(function(x,y) merge(x,y, by = "sample"), list(factor1_df, factor2_df, factor3_df, factor4_df, factor5_df, factor6_df))
colnames(factors_df) <- c("sample", "Factor1", "Factor2", "Factor3", "Factor4", "Factor5", "Factor6")
head(factors_df)
write.csv(factors_df, "NEWtop200_MOFA_factors", row.names = FALSE)
 
```



