---
title: "Protein to Gene name"
author: "Anna Österberg"
date: "2024-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning  = FALSE)
```

## Functions for converting protein names to gene names for GO enrichment analysis 

```{r}
#Loading needed libraries 
library(tidyverse)
```


```{r}
#Loading data
#Loading list of reference proteins
data <- read.csv("/home/aosterberg/Documents/DI_työ/PEVproteomics.csv",header = TRUE, dec = ",")
ref_proteins <- data %>% select(protein = X)
head(ref_proteins)

#Loading list of top proteins 
data <- read.csv("/home/aosterberg/top_proteins_0.5.csv")
top_proteins <- data %>% select(protein = feature)
head(top_proteins)

#Loading Uniprot list, saving only columns containing protein and gene names 
df <- read.delim("/home/aosterberg/Documents/NEWuniprot.tsv", header = TRUE)[,-c(1:3,5)]
```


```{r}
#We remove contents inside brackets explaining what proteins are cleaved into as it aids in matching proteins between lists 
remove_cleaved <- function(protein){
  str_replace(protein, "\\[.*", "")
}

df <- df %>% mutate(across(everything(), remove_cleaved))
print(df[1970,]) #We test the function 
```


```{r}
#We create a function separating protein names inside () into separate columns
df_mod <- df %>% 
  separate(Protein.names, into = paste0("col", 1:10), sep = "\\(", fill = "right", extra = "drop") %>% 
  mutate(across(everything(), ~ str_replace_all(., fixed(")"), ""))) %>% 
  mutate(across(everything(), ~str_trim(.)))
colnames(df_mod)<- c("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8", "col9","col10", "gene")
head(df_mod)

```


```{r}
#We create function that returns matching protein names from reference/top lists to Uniprot list 
compare_prot_names <- function(df1, df2){
  df2_long <- df2 %>% pivot_longer(cols = col1:col10, names_to = "protein_column", values_to = "protein_name")
  
  matches <- df1 %>% 
    left_join(df2_long, by = c("protein" = "protein_name")) %>% 
    select(protein, gene) %>% 
    distinct()
  
  matches
}
```


```{r}
#We create a list of the gene names from top/reference lists 
top_genes <- compare_prot_names(top_proteins, df_mod)
print(top_genes)
print(top_genes$protein[(which(is.na(top_genes$gene)))]) #we display missing gene names to be added manually 
write.table(top_genes$gene[!is.na(top_genes$gene)], "top_genes_0.5.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

#
ref_genes <- compare_prot_names(ref_proteins, df_mod)
head(ref_genes)
print(ref_genes$protein[(which(is.na(ref_genes$gene)))])
write.table(ref_genes$protein[(which(is.na(ref_genes$gene)))], "missing_genes", row.names  =FALSE, col.names = FALSE, quote = FALSE) #we create a list of missing gene names to be added manually 
write.table(ref_genes$gene[!is.na(ref_genes$gene)], "ref_genes.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

```
